env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  no-console: off
  max-len: off
  no-new: off
  no-use-before-define: off
  max-classes-per-file: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true